### ISSUE TITLE
Consider handling bad rectangles

### ISSUE THREAD

**Issue by mlissner** [freelawproject/x-ray#3]
This is easily the most common error, and probably an easy one to find. Just look for black rectangle objects on top of text. As a first pass, you could probably just look for black rectangles, but I've heard rumors that's how underlines are stored in PDFs. Here's a good example:

https://www.courtlistener.com/recap/gov.uscourts.dcd.190597/gov.uscourts.dcd.190597.471.0_6.pdf

**Comment by ZavierHenry** [comment]
Yes, black rectangle objects are one way to make an underline in a PDF. The example is actually using black rectangles for both underlines and redactions.

Example underline (from page 5) 

    144 680.16 260.03 -.6 re

Example redaction (also from page 5)  

    207.71 526.8 332.28 -13.8 re

I guess the easiest thing to do is just look for black rectangles that are tall enough to not be underlines. Even footnote redactions shouldn't be as short as underlines so that should work.

**Comment by mlissner** [comment]
Another example: https://www.courtlistener.com/docket/4573388/22/4/six4three-llc-v-facebook-inc/

**Comment by mlissner** [comment]
Another: https://www.courtlistener.com/docket/4512572/73/malibu-media-llc-v-doe/

**Comment by mlissner** [comment]
Another: https://storage.courtlistener.com/recap/gov.uscourts.wawd.296750/gov.uscourts.wawd.296750.57.0.pdf

**Comment by mlissner** [comment]
I haven't checked all of these examples, but rectangles with text under them are precisely what the currently released version supports, so I think we can call this done and just file bugs with the functionality as they arise.
